# Generated by Django 5.2.15 on 2026-06-10 07:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=20, unique=True)),
                ('stock_name', models.CharField(max_length=50)),
                ('market', models.CharField(choices=[('KOSPI', 'KOSPI'), ('KOSDAQ', 'KOSDAQ'), ('KONEX', 'KONEX'), ('OTHER', '기타')], default='KOSPI', max_length=20)),
                ('sector', models.CharField(choices=[('SEMICONDUCTOR', '반도체'), ('AUTO', '자동차'), ('FINANCE', '금융'), ('PLATFORM', '플랫폼'), ('BATTERY', '2차전지'), ('BIO', '바이오'), ('TELECOM', '통신'), ('GAME_ENTERTAINMENT', '게임/엔터'), ('CONSUMER', '유통/소비재'), ('ENERGY_CHEMICAL', '에너지/화학'), ('SHIP_MACHINE', '조선/기계'), ('ETC', '기타')], default='ETC', max_length=30)),
                ('industry', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('risk_level', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음')], default='MEDIUM', max_length=20)),
                ('size_type', models.CharField(choices=[('LARGE', '대형주'), ('MID', '중형주'), ('SMALL', '소형주'), ('UNKNOWN', '미분류')], default='UNKNOWN', max_length=20)),
                ('stability_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('growth_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('dividend_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('volatility_score', models.PositiveSmallIntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_recommendable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['stock_code'],
            },
        ),
        migrations.CreateModel(
            name='StockQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_price', models.PositiveIntegerField()),
                ('change_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('quote_time', models.DateTimeField()),
                ('delay_minutes', models.PositiveSmallIntegerField(default=20)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quote', to='stocks.stock')),
            ],
            options={
                'ordering': ['stock__stock_code'],
            },
        ),
        migrations.CreateModel(
            name='StockPriceDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_date', models.DateField()),
                ('open_price', models.PositiveIntegerField()),
                ('high_price', models.PositiveIntegerField()),
                ('low_price', models.PositiveIntegerField()),
                ('close_price', models.PositiveIntegerField()),
                ('volume', models.BigIntegerField(default=0)),
                ('change_rate', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_prices', to='stocks.stock')),
            ],
            options={
                'ordering': ['-trade_date'],
                'constraints': [models.UniqueConstraint(fields=('stock', 'trade_date'), name='unique_stock_trade_date')],
            },
        ),
    ]
