# Generated by Django 5.2.15 on 2026-06-10 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('operating_profit', models.BigIntegerField(blank=True, null=True)),
                ('net_income', models.BigIntegerField(blank=True, null=True)),
                ('total_assets', models.BigIntegerField(blank=True, null=True)),
                ('total_liabilities', models.BigIntegerField(blank=True, null=True)),
                ('total_equity', models.BigIntegerField(blank=True, null=True)),
                ('debt_ratio', models.FloatField(blank=True, null=True)),
                ('roe', models.FloatField(blank=True, null=True)),
                ('roa', models.FloatField(blank=True, null=True)),
                ('eps', models.FloatField(blank=True, null=True)),
                ('bps', models.FloatField(blank=True, null=True)),
                ('per', models.FloatField(blank=True, null=True)),
                ('pbr', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='StockMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_1m', models.FloatField(blank=True, null=True)),
                ('return_3m', models.FloatField(blank=True, null=True)),
                ('return_1y', models.FloatField(blank=True, null=True)),
                ('return_3y', models.FloatField(blank=True, null=True)),
                ('volatility_1y', models.FloatField(blank=True, null=True)),
                ('max_drawdown_1y', models.FloatField(blank=True, null=True)),
                ('avg_volume_3m', models.BigIntegerField(blank=True, null=True)),
                ('financial_score', models.FloatField(blank=True, null=True)),
                ('momentum_score', models.FloatField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('total_score', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='stockquote',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='stockpricedaily',
            name='unique_stock_trade_date',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='description',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='dividend_score',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='growth_score',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='risk_level',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='size_type',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stability_score',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='volatility_score',
        ),
        migrations.AddField(
            model_name='stock',
            name='corp_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='stock',
            name='corp_registration_no',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='stock',
            name='isin_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_synced_bas_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='market_cap',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='market',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='stockpricedaily',
            name='change_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='stockquote',
            name='change_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddConstraint(
            model_name='stockpricedaily',
            constraint=models.UniqueConstraint(fields=('stock', 'trade_date'), name='unique_stock_daily_price'),
        ),
        migrations.AddField(
            model_name='financialstatement',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financials', to='stocks.stock'),
        ),
        migrations.AddField(
            model_name='stockmetric',
            name='stock',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metric', to='stocks.stock'),
        ),
        migrations.AddConstraint(
            model_name='financialstatement',
            constraint=models.UniqueConstraint(fields=('stock', 'year'), name='unique_stock_financial_year'),
        ),
    ]
